[language-server.hyprls]
command = "hyprls"

[[language]]
name = "hyprlang"
language-servers = ["hyprls"]

# web dev ---------------------------------------------------------------------

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = { typescript = { tsdk = "/home/stormblessed/.bun/install/global/node_modules/typescript/lib" }, environment = "node" }

[[language]]
name = "astro"
auto-format = true
language-servers = ["astro-ls"]

[[language]]
name = "javascript"
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "tsx"
auto-format = true
language-servers = ["typescript-language-server"]

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "scss"
language-servers = ["vscode-css-language-server"]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]

[[language]]
name = "svelte"
auto-format = true
roots = ["svelte.config.js"]
language-servers = ["tailwindcss-ls", "svelteserver"]


# server ----------------------------------------------------------------------
[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "sql"
language-servers = ["sql-language-server"]

[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

# config ----------------------------------------------------------------------
[[language]]
name = "toml"
formatter = { command = "dprint", args = ["fmt", "--stdin", "toml"] }
auto-format = true

[[language]]
name = "json"
auto-format = true
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "bash"
formatter = { command = "dprint", args = ["fmt", "--stdin", "sh"] }
auto-format = true

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"
